//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int IdMascota { get; set; }
        public string Emfermedades { get; set; }
        public string Vacunas { get; set; }
        public decimal Peso { get; set; }
    }
}
