//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int IdMascota { get; set; }
        public string Categoria { get; set; }
        public string NombreMascota { get; set; }
        public int Telefono { get; set; }
        public string Raza { get; set; }
        public string Edad { get; set; }
        public string Sexo { get; set; }
        public string Acudiente { get; set; }
    }
}
